### ISSUE TITLE
Reverse Proxy Support?

### ISSUE THREAD

**Issue by sameleff** [ich777/docker-portfolio-performance#2]
I was able to get this up and running easily using the readme, but I was hoping to be able to use nginx as a reverse proxy (as I do with my other services) so that I do not need to remember IP address and ports. The subfolders in the [GUI address](https://github.com/ich777/docker-portfolio-performance#webgui-address-httpserveripportvnchtmlautoconnecttrue) are tripping me up, namely the `/vnc.html?autoconnect=true` portion. Firstly, will this work with a reverse proxy? Secondly, assuming yes to my first question, any advice on what I need to change in my nginx config?

Here is my nginx server block:
```
server {
    listen 443 ssl http2;
    server_name <mydomain>.duckdns.org;

    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        include /config/nginx/internal_only.conf;
        proxy_pass http://192.168.1.38:8088/vnc.html?autoconnect=true;
    }
} 
```

**Comment by ich777** [comment]
Please take a look at the README.md over [here](https://github.com/ich777/docker-debian-bookworm/blob/master/README.md#reverse-proxy-with-nginx-example).

Hope that helps.

**Comment by sameleff** [comment]
Brilliant, that was exactly it. Thanks very much!
